Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('1','Adobe Photoshop',' An image editing software developed and manufactured by Adobe Systems Inc. Photoshop is considered one of the leaders in photo editing software. ','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('2','C++','C++ is a general-purpose object-oriented programming (OOP) language, developed by Bjarne Stroustrup, and is an extension of the C language.','advanced');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('3','BASH','Bash is a Unix shell and command language written by Brian Fox for the GNU Project as a free software replacement for the Bourne shell.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('4','HTML','First developed by Tim Berners-Lee in 1990, HTML is short for HyperText Markup Language. HTML is used to create electronic documents (called pages) that are displayed on the World Wide Web.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('5','Git','Git is a version control system for tracking changes in computer files.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('6','Java','Java is a general purpose, high-level programming language developed by Sun Microsystems.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('7','jQuery','jQuery is a cross-platform JavaScript library designed to simplify the client-side scripting of HTML.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('8','Javascript','Javascript is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('9','C','C is a general-purpose, imperative computer programming language.','advanced');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('10','Linux','Linux is a name which broadly denotes a family of free and open-source software operating system distributions built around the Linux kernel.','advanced');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('11','MacIntosh OS','MacIntosh OS is the current series of Unix-based graphical operating systems developed and marketed by Apple Inc. designed to run on Apple''s Macintosh computers ("Macs").','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('12','JDBC','JDBC is an application programming interface (API) for the programming language Java, which defines how a client may access a database.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('13','Oracle','Oracle is a relational database management system.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('14','MySQL','MySQLis a relational database management system','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('15','Microsoft Word','Microsoft Word is a word processor developed by Microsoft.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('16','MongoDB','MongoDB is a free and open-source cross-platform document-oriented database program.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('17','Swift','Swift is a programming language developed by Apple Inc.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('18','Go','Go a programming language developed by Google.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('19','Haskell','Haskell is a standardized pure functional programming language with non-strict semantics.','advanced');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('20','Wireshark','Wireshark is a free and open source packet analyzer.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('21','YouTube','YouTube is an American video-sharing website.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('22','Unix','Unix is a family of multitasking, multiuser computer operating systems that derive from the original ATT Unix.','advanced');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('23','Python','Python is a programming language.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('24','Microsoft Windows','Microsoft Windows, or simply Windows, is a metafamily of graphical operating systems developed, marketed, and sold by Microsoft.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('25','Mobile Application Design','The development of mobile applications.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('26','Heroku','Heroku is a cloud platform as a service (PaaS) supporting several programming languages that is used as a web application deployment model.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('27','Facebook','Facebook is a social media website.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('28','Database Software','General relational database and software knowledge.','medium');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('29','CSS','Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language.','beginner');
Insert into KNOWLEDGE_SKILL (KS_CODE,TITLE,DESCRIPTION,KS_LEVEL) values ('30','VMWare','VMWare is a company that provides cloud computing and platform virtualization software and services.','beginner');
