Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('COM2020','1',2015,to_date('12-AUG-15','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('COM2020','2',2015,to_date('12-AUG-15','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('LSAT1001','1',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('LSAT1001','2',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('BUSI2020','1',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('BUSI2020','2',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('UDW1000','1',2015,to_date('10-DEC-15','DD-MON-RR'),'training company','online-selfpaced');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('UDW1000','2',2015,to_date('10-DEC-15','DD-MON-RR'),'training company','online-selfpaced');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2121','1',2014,to_date('10-MAY-14','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2121','2',2014,to_date('10-MAY-14','DD-MON-RR'),'university','online-selfpaced');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2120','1',2015,to_date('10-DEC-15','DD-MON-RR'),'training company','online-selfpaced');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2120','2',2015,to_date('10-DEC-15','DD-MON-RR'),'training company','online-selfpaced');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4125','1',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4125','2',2016,to_date('15-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4101','1',2016,to_date('12-AUG-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4101','2',2016,to_date('12-AUG-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI1583','1',2015,to_date('12-AUG-15','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI1583','2',2015,to_date('12-AUG-15','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4350','1',2011,to_date('11-DEC-11','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4350','2',2011,to_date('11-DEC-11','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('MATH1115','1',2011,to_date('11-MAY-11','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('MATH1115','1',2014,to_date('11-DEC-14','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2450','1',2017,to_date('11-DEC-17','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2450','2',2017,to_date('11-DEC-17','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2125','1',2016,to_date('11-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2125','2',2016,to_date('11-DEC-16','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI4401','1',2014,to_date('11-MAY-14','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI1581','1',2017,to_date('05-MAY-17','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI1581','2',2017,to_date('05-MAY-17','DD-MON-RR'),'university','online-sync');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI2467','1',2014,to_date('05-MAY-14','DD-MON-RR'),'university','classroom');
Insert into SECTION (C_CODE,SEC_NO,YEAR,COMPLETE_DATE,OFFERED_BY,FORMAT) values ('CSCI3301','1',2017,to_date('05-MAY-17','DD-MON-RR'),'training company','classroom');
